---
apiVersion: litmuschaos.io/v1alpha1
description:
  message: |
    Kill all openebs control plane pod and check if gets scheduled again
kind: ChaosExperiment
metadata:
  labels:
    litmuschaos.io/name: openebs
  name: openebs-control-plane-chaos
  version: 0.1.3
spec:
  definition:
    scope: Namespaced
    permissions:
      - apiGroups:
          - ""
          - "litmuschaos.io"
          - "batch"
          - "apps"
        resources:
          - "pods"
          - "pods/log"
          - "deployments"
          - "events"
          - "jobs"
          - "configmaps"
          - "chaosengines"
          - "chaosexperiments"
          - "chaosresults"
        verbs:
          - "create"
          - "list"
          - "get"
          - "patch"
          - "update"
          - "delete"
      - apiGroups:
          - ""
        resources:
          - "nodes"
        verbs:
          - "get"
          - "list"
      
    image: "litmuschaos/ansible-runner:latest"
    args:
    - -c
    - ansible-playbook ./experiments/openebs/openebs-nfs-provisioner-kill/openebs_nfs_provisioner_kill_ansible_logic.yml -i /etc/ansible/hosts -vv; exit 0
    command:
    - /bin/bash
    env:
    - name: ANSIBLE_STDOUT_CALLBACK
      value: 'default'

    - name: TARGET_CONTAINER
      value: ''

    # Period to wait before injection of chaos in sec
    - name: RAMP_TIME
      value: ''

    # It supports pumba and containerd 
    - name: LIB
      value: 'pumba'

    # provide the chaos interval
    - name: CHAOS_INTERVAL
      value: '10'

    # provide the total chaos duration
    - name: TOTAL_CHAOS_DURATION
      value: '20'

    # LIB_IMAGE can be - gaiaadm/pumba:0.6.5, gprasath/crictl:ci
    # For pumba image use: gaiaadm/pumba:0.6.5
    # For containerd image use: gprasath/crictl:ci
    - name: LIB_IMAGE  
      value: 'gaiaadm/pumba:0.6.5' 

    labels:
      name: openebs-nfs-kill-chaos